"""
Excel export API route — Firestore-backed.
"""
import io
from datetime import datetime
from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from auth.auth import get_current_user, require_role, db_firestore

router = APIRouter(prefix="/api/export", tags=["Export"])


@router.get("/excel")
def export_to_excel(
    current_user: dict = Depends(require_role("admin", "officer")),
):
    try:
        from openpyxl import Workbook
        from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    except ImportError:
        from fastapi.responses import JSONResponse
        return JSONResponse(
            status_code=500,
            content={"detail": "openpyxl not installed. Run: pip install openpyxl"}
        )

    db = db_firestore
    wb = Workbook()

    # Styling
    header_font = Font(name="Calibri", bold=True, color="FFFFFF", size=11)
    header_fill = PatternFill(start_color="1F3864", end_color="1F3864", fill_type="solid")
    header_alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    thin_border = Border(
        left=Side(style="thin", color="CCCCCC"),
        right=Side(style="thin", color="CCCCCC"),
        top=Side(style="thin", color="CCCCCC"),
        bottom=Side(style="thin", color="CCCCCC"),
    )
    risk_fills = {
        "High": PatternFill(start_color="FFE0E0", end_color="FFE0E0", fill_type="solid"),
        "Medium": PatternFill(start_color="FFF3CD", end_color="FFF3CD", fill_type="solid"),
        "Low": PatternFill(start_color="D4EDDA", end_color="D4EDDA", fill_type="solid"),
    }

    # Sheet 1: Persons
    ws_persons = wb.active
    ws_persons.title = "Persons"
    person_headers = [
        "Person ID", "Full Name", "Date of Birth", "Gender", "Nationality",
        "Address", "Government ID", "Record Status", "Risk Level",
        "Last Seen Location", "Has Face Data", "Created At"
    ]
    for col, header in enumerate(person_headers, 1):
        cell = ws_persons.cell(row=1, column=col, value=header)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_alignment
        cell.border = thin_border

    persons = list(db.collection("persons").stream())
    for row_idx, doc in enumerate(persons, 2):
        p = doc.to_dict()
        data = [
            doc.id, p.get("full_name", ""), p.get("date_of_birth", "N/A"),
            p.get("gender", "N/A"), p.get("nationality", "N/A"),
            p.get("address", "N/A"), p.get("government_id_number", "N/A"),
            p.get("record_status", "N/A"), p.get("risk_level", "N/A"),
            p.get("last_seen_location", "N/A"),
            "Yes" if p.get("face_embedding_encrypted") else "No",
            p.get("created_at", "N/A"),
        ]
        for col, value in enumerate(data, 1):
            cell = ws_persons.cell(row=row_idx, column=col, value=value or "N/A")
            cell.border = thin_border
            cell.alignment = Alignment(vertical="center")
            if col == 9 and value in risk_fills:
                cell.fill = risk_fills[value]
                cell.font = Font(bold=True)

    # Sheet 2: Criminal Records
    ws_records = wb.create_sheet("Criminal Records")
    record_headers = [
        "Record ID", "Person ID", "Crime Type", "Crime Description",
        "Case Number", "Date of Offense", "Arrest Date", "Conviction Status",
        "Sentence Details", "Agency", "Court", "Last Updated"
    ]
    for col, header in enumerate(record_headers, 1):
        cell = ws_records.cell(row=1, column=col, value=header)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_alignment
        cell.border = thin_border

    records = list(db.collection("criminal_records").stream())
    for row_idx, doc in enumerate(records, 2):
        r = doc.to_dict()
        data = [
            doc.id, r.get("person_id", ""), r.get("crime_type", "N/A"),
            r.get("crime_description", "N/A"), r.get("case_number", "N/A"),
            r.get("date_of_offense", "N/A"), r.get("arrest_date", "N/A"),
            r.get("conviction_status", "N/A"), r.get("sentence_details", "N/A"),
            r.get("law_enforcement_agency", "N/A"), r.get("court_name", "N/A"),
            r.get("last_updated", "N/A"),
        ]
        for col, value in enumerate(data, 1):
            cell = ws_records.cell(row=row_idx, column=col, value=value or "N/A")
            cell.border = thin_border

    # Sheet 3: Summary
    ws_summary = wb.create_sheet("Summary")
    ws_summary.cell(row=1, column=1, value="Criminal Recognition System - Export").font = Font(bold=True, size=14)
    ws_summary.cell(row=2, column=1, value=f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    ws_summary.cell(row=3, column=1, value=f"Generated by: {current_user.get('full_name', 'Unknown')}")
    ws_summary.cell(row=5, column=1, value="Total Persons:").font = Font(bold=True)
    ws_summary.cell(row=5, column=2, value=len(persons))
    ws_summary.cell(row=6, column=1, value="Total Criminal Records:").font = Font(bold=True)
    ws_summary.cell(row=6, column=2, value=len(records))

    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)

    filename = f"criminal_records_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"
    return StreamingResponse(
        buffer,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )
